### ISSUE TITLE
[Question/suggestion] plugin download to build/ instead of src/

### ISSUE THREAD

**Issue by supersaiyansubtlety** [gbl/CrowdinTranslate#18]
Is it possible to configure the plugin to put downloaded files in `build/main/assets/<modid>/lang` instead of `src/main/assets/<modid>/lang`?

I'd like use `processResources { }` to process my source lang file, and I don't want the local version with placeholder tokens to be overwritten by the version on crowdin with those tokens already replaced.

`build/` also seems to me like a more fitting place for auto-downloaded files used in built jars, but that's just preference.

**Comment by gbl** [comment]
Sorry, there's no such option. You'd have to create a fork that replaces the `rootDir` string in line 414 of CrowdinTranslate.java.

I like to have the lang files in src/ where they normally belong, so I have them in git, can see their history, and also compile a mod when crowdin is down if necessary.
